name: chill
description: Backup tool for incremental offline (cold storage) archives.
version: 0.1.0
repository: https://github.com/agilord/chill

topics:
 - archive
 - backup
 - tool

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  buffer: ^1.2.2
  # crypto: ^3.0.3
  cryptography: ^2.7.0
  file: ^7.0.0
  mime: ^1.0.4
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
